package epichacks.events;

/**
 * The {@code EventDirection} enum represents the direction of an event, which can be either "INCOMING" or "OUTGOING".
 * Event directions are used to specify the flow or direction of an event within a system or process.
 */
public enum EventDirection {
    /**
     * Represents an event that is incoming or directed towards the system or component.
     * Typically, "INCOMING" events originate from external sources or users.
     */
    INCOMING,

    /**
     * Represents an event that is outgoing or directed away from the system or component.
     * Typically, "OUTGOING" events are generated by the system or component for external consumption.
     */
    OUTGOING
}

